# Generated by Django 5.1.5 on 2025-02-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture_user_role_mentee_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('CA', 'Canada')], default='Canada', max_length=100),
        ),
    ]
