# Generated by Django 5.1.5 on 2025-02-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_mentor_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='industry',
        ),
        migrations.AddField(
            model_name='mentor',
            name='industries',
            field=models.ManyToManyField(related_name='mentors', to='users.industry'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
