# Generated by Django 5.1.5 on 2025-02-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_mentor_asap_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approach',
            options={'verbose_name': 'Approach', 'verbose_name_plural': 'Approaches'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.RemoveField(
            model_name='approach',
            name='description',
        ),
        migrations.RemoveField(
            model_name='approach',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='mentor',
        ),
        migrations.AddField(
            model_name='approach',
            name='name',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='mentor',
            name='approaches',
            field=models.ManyToManyField(related_name='mentors', to='users.approach'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='education',
            field=models.ManyToManyField(related_name='mentors', to='users.education'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='offers',
            field=models.ManyToManyField(related_name='mentors', to='users.offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
    ]
