# Generated by Django 5.1.5 on 2025-02-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_approach_options_alter_industry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='country',
            field=models.CharField(choices=[('United States', 'United States'), ('Canada', 'Canada')], default='Canada', max_length=100),
        ),
    ]
